services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_PAT=${GITHUB_PAT}
    ports:
      - 80:80   # 기존 서비스 포트
    env_file:
      - .env
    command: sleep infinity
